### ISSUE TITLE
Dashboard completely disappear after using custom

### ISSUE THREAD

**Issue by Bios-dude** [custom-cards/upcoming-media-card#67] opened 2021-04-03 13:27 UTC
## Config YAML:  
```
views:
  - badges: []
    cards:
      - type: 'custom:upcoming-media-card'
        entity: sensor.sonarr_upcoming
```

## Screenshots: 
![Screenshot_32](https://user-images.githubusercontent.com/63623759/113479757-0181a180-94bb-11eb-9f71-bdc1bd4f69af.png)

**Comment by Bios-dude** [comment] 2021-04-03 13:36
![Screenshot_33](https://user-images.githubusercontent.com/63623759/113479978-2a566680-94bc-11eb-8b4a-44ec4825bfd0.png)
Just for information if my radarr and sonarr integration working fine, if i put the card type again, it will completely disappear like above

**Comment by luisgarcia87** [comment] 2021-04-27 04:12
My dashboard was not loading at all after updating Home Assistant to core-2021.4.5 
I troubleshoot the lovelace by removing custom add-ons and see which one was causing the crash. It was the upcoming-media-card, after removing it from the RAW configuration editor the UI loaded and everything was working fine.

**Comment by jds11111** [comment] 2021-04-27 07:02
I had the same thing, but fixed it with reinstalling. I think something changed with integration. IIRC, the js files are stored somewhere else, so if you follow the installation instructions, the resources have moved. I then put the cards back in the dashboard and it worked.

**Comment by oziee** [comment] 2021-09-08 03:44
the built in sonarr component integration does not supply this front_end card with the correct json data its programmed to look for..
this is why is doesn't work anymore

**Comment by Belazriel1** [comment] 2021-09-14 03:23
>you have to use the sonarr integration from here (not the built in HA integration)

I realize that this was my fault for not reading the directions properly when adding everything, but would it be possible to have attempting to use the default HA implementation cause a visible error? I made this mistake as well as Bios-Dude and I'm guessing that others have as well and possibly just give up and move on.

**Comment by mkanet** [comment] 2024-05-30 19:23
Closing this issue since a lot has changed since this issue was opened.  If you still haven't found a solution/workaround, you can open a new issue describing how to reproduce it.

**Closed by mkanet** 2024-05-30 19:23 UTC
